### PR TITLE
Created a dockerContainer to simplify the developer setup and upgraded to a newer version of TensorFlow

### PR DESCRIPTION
**Pull request by justinsmits**

### CODE REVIEW

**Comment by justinsmits** [comment]
Hi @liuhh02 , let me know if it's necessary to fix those failing checks and/or if you have any questions about the pull request!

**Comment by justinsmits** [comment]
Hi @liuhh02 , friendly bump :) If you are not really open to enhancements to the project, totally cool, just let me know. I am happy to continue in a forked off repo. Thanks!

**Comment by liuhh02** [comment]
> Hi @liuhh02 , friendly bump :) If you are not really open to enhancements to the project, totally cool, just let me know. I am happy to continue in a forked off repo. Thanks!

Hi, thank you for your pull request! My apologies for the late reply, I must have missed the first notification. I wholeheartedly welcome any improvements to the repo!

**Comment by justinsmits** [comment]
no worries, thank you! lmk if you have any questions about the changes. Thanks!

**Pull request merged**
